const waterDictionary = {
    eau: "Essentiel pour toute vie.",
    rivière: "Coule vers une plus grande étendue.",
    mer: "Plus petite qu'un océan.",
    océan: "La plus grande étendue d'eau.",
    ruisseau: "Petit cours d'eau en mouvement.",
    lac: "Étendue d'eau intérieure.",
    étang: "Petit lac peu profond.",
    crique: "Petit cours d'eau étroit.",
    torrent: "Semblable à un petit ruisseau.",
    vague: "Ondulation de surface d'eau en mouvement.",
    marée: "Mouvement de l'eau par la lune.",
    courant: "Direction du flux d'eau.",
    port: "Abri pour les navires ou les bateaux.",
    baie: "Zone d'eau le long d'une côte courbée.",
    lagune: "Mer peu profonde connectée à l'eau.",
    marais: "Zones humides avec de l'herbe, de la végétation.",
    zoneHumide: "Terrain saturé d'eau.",
    estuaire: "Où une rivière rencontre l'océan.",
    canal: "Passage d'eau artificiel.",
    chenal: "Étendue d'eau étroite.",
    fjord: "Profonde entrée avec des falaises.",
    golfe: "Grande zone d'entrée maritime.",
    delta: "Terrain à l'embouchure d'une rivière.",
    réservoir: "Stockage d'eau artificiel.",
    source: "Eau émergeant du sol.",
    geyser: "Eau chaude jaillissant périodiquement.",
    cascade: "Petite série de chutes d'eau.",
    chuteDEau: "Eau s'écoulant sur un bord.",
    aqueduc: "Canal d'approvisionnement en eau artificiel.",
    bassin: "Zone collectant de l'eau.",
    tourbillon: "Mouvement en spirale de l'eau.",
    fontaine: "Eau jaillissant vers le haut.",
    rivage: "Terrain au bord de l'eau.",
    côte: "Terrain le long de la mer.",
    plage: "Zone sablonneuse près de l'eau.",
    récif: "Structure de corail sous-marine.",
    île: "Terrain entouré d'eau.",
    archipel: "Groupe d'îles ensemble.",
    criqueAbritée: "Petite baie abritée.",
    détroit: "Eau étroite entre des terres.",
    brasDeMer: "Large canal ou entrée d'eau.",
    quai: "Plateforme pour charger des navires.",
    jetée: "Structure s'étendant dans l'eau.",
    portMaritime: "Lieu pour charger des navires.",
    saumure: "Eau ou solution salée.",
    oasis: "Eau dans une zone désertique.",
    voieNavigable: "Route navigable d'eau.",
    barrage: "Bloque l'eau pour créer un réservoir.",
    irrigation: "Arrosage des cultures artificiellement.",
    hydrologie: "Étude du mouvement de l'eau.",
    sousMarin: "Véhicule ou navire sous l'eau.",
    nautique: "Lié à la navigation, à l'eau.",
    éclaboussure: "Petite giclée d'eau.",
    ondulation: "Petites vagues sur l'eau.",
    inondation: "Débordement d'eau sur terre.",
    aquifère: "Couche de stockage d'eau souterraine.",
    navigation: "Voyage à travers les surfaces d'eau.",
    bouée: "Marqueur flottant dans l'eau.",
    mouillé: "Opposé de sec, couvert d'eau.",
    détrempé: "Excessivement humide ou trempé.",
    saturation: "Complètement rempli d'eau.",
    brume: "Fine pulvérisation d'eau.",
    pulvérisation: "Eau dispersée en gouttelettes.",
    précipitation: "Pluie, neige ou grêle qui tombe.",
    pluie: "Gouttelettes d'eau des nuages.",
    bruine: "Pluie légère et douce.",
    averse: "Pluie intense tombant rapidement.",
    tempête: "Forts vents avec pluie.",
    ouragan: "Tempête tropicale avec du vent.",
    tsunami: "Événement de vague massive dans l'océan.",
    maréeBasse: "Relatif aux marées de l'océan.",
    submerger: "Complètement sous l'eau.",
    immerger: "Plonger complètement dans l'eau.",
    tremper: "Tremper complètement avec de l'eau.",
    humidité: "Petite quantité d'eau présente.",
    vapeur: "Eau sous forme de gaz.",
    iceberg: "Grande masse de glace flottante.",
    glacier: "Rivière de glace en mouvement lent.",
    polaire: "Régions froides près des pôles.",
    marin: "Lié à la vie océanique.",
    pélagique: "Mer ouverte ou océan.",
    plancton: "Petits organismes océaniques.",
    salinité: "Niveau de sel dans l'eau.",
    profondeur: "Distance sous la surface de l'eau.",
    hautFonds: "Eau peu profonde avec du sable.",
    dune: "Colline de sable près de l'eau.",
    corail: "Organismes marins à base de squelette.",
    surf: "Vagues se brisant près du rivage.",
    navigationDePlaisance: "Voyage en petit bateau.",
    pêche: "Attraper des poissons dans l'eau.",
    voile: "Voyager sur l'eau avec le vent.",
    plongée: "Activité de nage sous l'eau.",
    plongéeAvecTuba: "Nager sous l'eau peu profonde avec équipement."
};
 export default waterDictionary  